/**
 * Copyright (c) 2013 Oculus Info Inc.
 * http://www.oculusinfo.com/
 *
 * Released under the MIT License.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
define(['jquery'], function($) {
    var GLOBAL_BARCHART = ['#FEABB9','#91278F','#89DBEC','#00909E','#D87DFC','#D87D40','#ABFED1','#8B9127','#FCBC7D','#D87DFC'],
		GLOBAL_BORDER = '#EEE',
		GLOBAL_HIGHLIGHT = '#AFA',
		GLOBAL_HOVER = '#AAF',
		GLOBAL_LABEL = '#076B88',
		GLOBAL_NOTIFIER = '#555',
		GLOBAL_RESIZE_BAR = '#EEE',
		GLOBAL_SELECTED_HOVER = '#00D100',//'#6B6',
		GLOBAL_TITLE_BAR = '#DEDEDE',
		GLOBAL_TOTAL = '#FEABB9';
	return {
		AGGREGATEMAP_TOTAL: GLOBAL_TOTAL,
		AGGREGATETIME_DEFAULT_LINE: '#222',
		AGGREGATETIME_LOCAL: '#0A0',
		AGGREGATETIME_NEW_TO_ADS: '#A00',
		AGGREGATETIME_NEW_TO_TOWN: '#A0A',
		APPWIDGET_RESIZE_BAR: GLOBAL_RESIZE_BAR,
		BARCHART_COLORS: GLOBAL_BARCHART,
		BARCHART_MISSING_DATA: '#D4D4D4',
		BORDER_DARK: '#DEDEDE',
		CASE_BORDER: GLOBAL_BORDER,
		CASE_HIGHLIGHT: GLOBAL_HIGHLIGHT,
		CASE_HOVER: GLOBAL_HOVER,
		CASE_DROP_HERE: '#808080',
		CASE_NOTIFIER: GLOBAL_NOTIFIER,
		CASE_PRIVATE: '#FAA',
		CASE_SELECTED_HOVER: GLOBAL_SELECTED_HOVER,
		CIRCLE_DECREASE: '#F22',
		CIRCLE_DEMOGRAPHIC: '#0F0',
		CIRCLE_HOVER: '#F08',
		CIRCLE_INCREASE: '#2F2',
		CIRCLE_SELECTED: '#80F',
		CIRCLE_TOTAL: GLOBAL_TOTAL,
//    	CIRCLE_TOTAL:'r(.5,.9)hsb(.9, 1, .75)-hsb(.9, .5, .25)',
		CIRCLE_VISITED: '#609',
		CLUSTER_ARRAY: GLOBAL_BARCHART,
		CLUSTER_ARRAY_NONE: '#FFF',
		CLUSTER_BORDER: '#808080',
		CLUSTER_HIGHLIGHT: GLOBAL_HIGHLIGHT,
		CLUSTER_HOVER: GLOBAL_HOVER,
		CLUSTER_LABEL: GLOBAL_LABEL,
		CLUSTER_RESIZE_BAR: GLOBAL_RESIZE_BAR,
		CLUSTER_SELECTED_HOVER: GLOBAL_SELECTED_HOVER,
		CLUSTER_TITLE_BAR: GLOBAL_TITLE_BAR,
		GRAPH_DOT_STROKE: '#222',
		GRAPH_RING_1: '#FFE3BB',
		GRAPH_RING_2: '#FFECD1',
		GRAPH_RING_3: '#FFF6E8',
		GRAPH_RING_4: '#FFF',
		LINK_PHONE: '#00909E',
		LINK_EMAIL: '#E48500',
		LINK_WEBSITE: '#D797DD',
		LINK_DEFAULT: '#00909E',
		LINK_SELECTED: GLOBAL_HIGHLIGHT,
		MAP_HIGHLIGHT: GLOBAL_HIGHLIGHT,
		MAP_HOVER: GLOBAL_HOVER,
		MAP_SELECTED_HOVER: GLOBAL_SELECTED_HOVER,
		MAP_TOTAL: GLOBAL_TOTAL,
		MENU_HOVER: GLOBAL_HOVER,
		MOVEMENT_CITY_LABEL_DEFAULT: '#F6F6F6',
		MOVEMENT_HIGHLIGHT: GLOBAL_HIGHLIGHT,
		MOVEMENT_HOVER: GLOBAL_HOVER,
		MOVEMENT_SELECTED_HOVER: GLOBAL_SELECTED_HOVER,
		MOVEMENT_TICK_DEFAULT: '#808080',
		MOVEMENT_TIMELINE_BACKGROUND: '#FFF',
		OVERVIEW_BORDER: GLOBAL_BORDER,
		OVERVIEW_DATA: '#FFF',
		OVERVIEW_HOVER: GLOBAL_HOVER,
		OVERVIEW_HIGHLIGHT: GLOBAL_HIGHLIGHT,
		OVERVIEW_TIMELINE_BORDER: '#86817D',
		SIDEPANEL_LABEL: GLOBAL_LABEL,
		SUMMARY_HOVER: GLOBAL_HOVER,
		SUMMARY_NOTIFIER: GLOBAL_NOTIFIER,
		TABLE_ATTRIBUTE_HOVER: '#77F',
		TABLE_BORDER: GLOBAL_BORDER,
		TABLE_BLURRED: '#FAA',
		TABLE_HIGHLIGHT: GLOBAL_HIGHLIGHT,
		TABLE_HOVER: GLOBAL_HOVER,
		TABLE_LABEL: GLOBAL_LABEL,
		TABLE_OVERLAY_BORDER: '#BBB',
		TABLE_SELECTED_HOVER: GLOBAL_SELECTED_HOVER,
		TABLE_TITLE_BAR: GLOBAL_TITLE_BAR,

		getBarchartColor: function(index) {
            var color = new aperture.Color(GLOBAL_BARCHART[index % GLOBAL_BARCHART.length]);
            // TODO: This is just a short term hack to modify our limited palette
            if (index+1 > GLOBAL_BARCHART.length) {
                color = color.hue(color.hue()-20*(index+1-GLOBAL_BARCHART.length));
            }
			return color;
		}
	}
});